# Validates Functions Framework with GCF buildpacks.
name: Buildpack Integration Test
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  ruby30-buildpack-test:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@kennethrosario/use-gcf-specific-builder
    with:
      http-builder-source: 'test/conformance'
      http-builder-target: 'http_func'
      cloudevent-builder-source: 'test/conformance'
      cloudevent-builder-target: 'cloudevent_func'
      prerun: 'test/conformance/prerun.sh ${{ github.sha }}'
      builder-runtime: 'ruby30'
